---
apiVersion: v1
kind: Secret
metadata:
  name: frontenda21qw-app-repo
  namespace: devhub
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/devhub-mad/frontenda21qw-app-gitops
